version: 2

project_name: mcp-wire

builds:
  - main: ./cmd/mcp-wire/main.go
    binary: mcp-wire
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/andreagrandi/mcp-wire/internal/app.Version={{.Version}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  name_template: "Release v{{ .Version }}"
  draft: false
  prerelease: auto

brews:
  - name: mcp-wire
    repository:
      owner: andreagrandi
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@github.com
    directory: Formula
    homepage: "https://github.com/andreagrandi/mcp-wire"
    description: "Install and configure MCP servers across AI coding tools"
    license: "MIT"
    test: |
      system "#{bin}/mcp-wire --version"
    install: |
      bin.install "mcp-wire"
